on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    name: Build Isabelle Release
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - run: sudo apt-get -y install 
      - run: ./do_release
