on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    name: Build Isabelle HOL
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - run: sudo apt-get update
      - run: sudo apt-get -y install default-jdk
      - run: env ISABELLE_JDK_HOME=$(dirname $(dirname $(readlink -f $(which javac)))) ./bin/isabelle components -a
      - run: env ISABELLE_JDK_HOME=$(dirname $(dirname $(readlink -f $(which javac)))) ./bin/isabelle build -b HOL
